name: tag-test

on:
  push:
    branches:
      - test

jobs:
  tag-test:
    runs-on: ubuntu-latest

    steps:
    - name: Set variables
      run: |
        VER=$(cat VERSION)
        echo "VERSION=$VER" >> $GITHUB_ENV
        
    - name: Print
      run: echo $DOCKERTAG
